.phony: install_linker_files


install_linker_scripts:
	mkdir -p $(FIDES_UTILITIES)
	mkdir -p $(FIDES_UTILITIES)/bin
	mkdir -p $(FIDES_UTILITIES)/bin/linker-scripts
	cp * $(FIDES_UTILITIES)/bin/linker-scripts/
